<a href="https://colab.research.google.com/github/Namrata3103-star/Key-Projects/blob/main/Basics%2C_Functions_%26_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(help("keywords"))


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

None


In [ ]:
x=float(input("Number1: "))
y=float(input("Number2: "))
average=(x+y)/2
print(average)

Number1: 22.5
Number2: 66.8
44.65


In [ ]:
x=float(input("Principal:"))
y=float(input("Rate:"))
z=float(input("Time"))
simple_interest=(x*y*z)/100
print("Simple Interest:",simple_interest)

Principal:100
Rate:2.5
Time1.5
Simple Interest: 3.75


In [ ]:
age=int(input("Age:"))
if age>18:
  print("Eligible to vote")
else:
  print("Not eligible to vote")

Age:5
Not eligible


In [ ]:
input_str='bmaunmdbraai'
message1=input_str[0:-1:2]
message2=input_str[1:len(input_str):2]
print(message1.rstrip('#')+','+message2.rstrip('#'))

bandra , mumbai


In [ ]:
x = 'len'
x[len(x * 2) - 5]

'e'

In [ ]:
sentence = 'This sentence needs to be split into words'
print(sentence.split()[5])

split


In [ ]:
if 4+9<10:
  print("true")
else:
  print("false")
print("true")

false
true


In [ ]:
inp=input()
Vowels='aeiouAEIOU'
for x in inp:
  if x in Vowels:
    inp=inp.replace(x,'#')
print(inp)


upgrad
#pgr#d


In [ ]:
import ast
L = ast.literal_eval(input())
L.sort(key=lambda i:i[1],reverse=True)
L

[(45,77), (88,87), (67,98), (33,31)]


[(67, 98), (88, 87), (45, 77), (33, 31)]

In [ ]:
input_str=input()
if input_str[0] in 'aeiou':
  print("YES")
else:
  print("NO")


beta
NO


In [ ]:
input_string = "I love Python"
k = [(i.upper(), len(i)) for i in input_string.split(' ')]
print(k)

[('I', 1), ('LOVE', 4), ('PYTHON', 6)]


In [ ]:
var = [i**2 for i in range(5)]
print(var)

[0, 1, 4, 9, 16]


In [ ]:
l1=[1,2,3,7]
l2=[4,5,6,9]
[x+y for x in l1 for y in l2]

[5, 6, 7, 10, 6, 7, 8, 11, 7, 8, 9, 12, 11, 12, 13, 16]

In [ ]:
def function(n):
  n=n+1
  return n
 
n=2
print(function(2))


3


In [ ]:
x=10
def func(x):
   x=20
print(x)
 
print(x)

10
10


In [ ]:
def samplefunc(msg,i=3):
  print(msg*i)
 
samplefunc('python',4)
samplefunc('program')

pythonpythonpythonpython
programprogramprogram


In [ ]:
f=lambda x:bool(x%2)
print(f(100)* f(101))

0


In [ ]:
l=(1, -2, -3, 4, 5)
def f1(x):
    return x//2
m1=map(f1, l)
print(list(m1))

[0, -1, -2, 2, 2]


In [ ]:
sample=[-4,2,5,-3]
ans=map(lambda x: x*2,sample)
print(list(ans))

[-8, 4, 10, -6]


In [ ]:
import functools
lis=[1, 2, 3, 4, 5]
m=functools.reduce(lambda x, y:x if x<y else y, lis)
print(m)

1


In [ ]:
lis=[1, 2, 3, 4, 5]
c=lis[0]
for i in range(len(lis)-1):
    if lis[i]<c:
       c=lis[i]
print(c)

1


In [ ]:
letters = ('d','i','a','s')
ans = list(map(lambda word: f"{word}x", letters))
print(ans)

['dx', 'ix', 'ax', 'sx']


In [ ]:
def sf(a):
    return a%4==0 and a%8!=0
m=filter(sf, range(10, 31))
print(list(m))

[12, 20, 28]


In [ ]:
import ast
L=input()
input_list=ast.literal_eval(L)
even=filter(lambda x:x%2==0,input_list)
print(list(even))

[500, 789, 2112, 9097, 5894, 9062, 8977, 1223, 773, 600]
[500, 2112, 5894, 9062, 600]


In [ ]:
import ast
L=input()
input_list=ast.literal_eval(L)
triple=map(lambda x:x*3,input_list)
print(list(triple))

[15, 71, 2, 9, 5, 6, 11, 3, 7, 6]
[45, 213, 6, 27, 15, 18, 33, 9, 21, 18]


In [ ]:
import ast
L=input()
input_list=ast.literal_eval(L)
encrypt1=map(lambda x:x.upper(),input_list)
encrypt2=map(lambda x:x[::-1],list(encrypt1))
print(list(encrypt2))

['Abhay', 'Aravind', 'Desilva', 'Darpan']
['YAHBA', 'DNIVARA', 'AVLISED', 'NAPRAD']


In [ ]:
import ast
L=input()
input_list=ast.literal_eval(L)
sorted_list=sorted(input_list,key=lambda i:(i['rank'],i['name']))
print(sorted_list)

[{ "name" : "Mohan", "rank" : 2}, { "name" : "Mandeep", "rank" : 2 },  { "name" : "Merut" , "rank" : 2 }]
[{'name': 'Mandeep', 'rank': 2}, {'name': 'Merut', 'rank': 2}, {'name': 'Mohan', 'rank': 2}]


In [ ]:
import ast
L1=input()
L2=input()
L3=input()
input_list1=ast.literal_eval(L1)
input_list2=ast.literal_eval(L2)
input_list3=ast.literal_eval(L3)
newL1=[i.lower() for i in input_list1]
newL2=[i.lower() for i in input_list2]
newL3=[i.lower() for i in input_list3]
intersect1=[i for i in newL1 if i in newL2]
intersect2=[i for i in intersect1 if i in newL3]
print(intersect2)

['Siddharth', 'Gaurav', 'Prasad', 'Kuldeep', 'karna']
['siddharth', 'Gaurav', 'Prasad', 'Kuldeep', 'karna']
['Siddharth', 'gaurav', 'PRASAD', 'KuLDEEp', 'KARNA']
['siddharth', 'gaurav', 'prasad', 'kuldeep', 'karna']


In [ ]:
import ast
L=input()
input_list=ast.literal_eval(L)
output=sorted(input_list,key=lambda x:len(x),reverse=True)
print(output)

[{4: 'Viking', 9: 'Happy', 10: 'Tony', 2: 'Rogers'}, {12: 'Vikram', 19: 'Vipan'}, {3: 'Kohli'}, {1: 'Ronaldo', 29: 'Harish'}]
[{4: 'Viking', 9: 'Happy', 10: 'Tony', 2: 'Rogers'}, {12: 'Vikram', 19: 'Vipan'}, {1: 'Ronaldo', 29: 'Harish'}, {3: 'Kohli'}]


In [ ]:
try:
    a=int(input("Please Enter an integer for A"))
    b=int(input("Please Enter an integer for B"))
except:
    print("Please input the valid integers")
    try:
        a=int(input("Please Enter an integer for A"))
        b=int(input("Please Enter an integer for B"))
    except:
        print("Handle it")
    finally:
        c=(a+b)/(a-b)
        print(c)
finally:
    print("Now I am executed ")
    

Please Enter an integer for At
Please input the valid integers
Please Enter an integer for A20
Please Enter an integer for B10
3.0
Now I am executed 


In [ ]:
def Temp(num):
  print("Temp is:",(num*9/5)+32)
 
Temp(32)

Temp is: 89.6


In [ ]:
def check(num):
  if num%2==0:
    print("even")
  else:
    print("odd")
check(10)

even


In [ ]:
num=int(input())
count=0
for i in range(1,num+1):
  if num%i==0:
    count=count+1
if count>2:
  print("Not prime")
else:
  print("Prime")


13
Prime


In [ ]:
import ast 
input_list=ast.literal_eval(input())
m=int(input())
n=int(input())
import numpy as np
array_1 = np.array(input_list)
final_array = array_1[array_1>m]
final_array1=final_array[final_array<n]
print(final_array1)

[ 1, 5, 9, 12, 15, 7, 12, 9 ]
12
6
[]


In [ ]:
import numpy as np
L=[[1,2,3],[4,5,6],[7,8,9]]
newL=np.array(L)
final_L=newL[:,0]
final_L

array([1, 4, 7])

In [ ]:
import numpy as np
output=np.arange(5,55,5)
print(output)


[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
import numpy as np
list_1=[[7, 13, 14],

[18, 10, 17],

[11, 12, 19]]
list_2=[16, 6, 1]
list_3=[[5, 8, 4, 3]]
array1=np.array(list_1)
array2=np.array(list_2)
array3=np.array(list_3)
array4=np.vstack((array1,array2))
array5 = np.transpose(array3)
final_array=np.hstack((array4,array5))
print(final_array)

[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [ ]:
a=np.array([1,2,3])
b=np.array([2,3,4])
np.transpose((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
dict2={"Name":{"Rohan":{"Roll_no":18,"Blood_grp":'O','Admission_no':14313},'Krishna':
              {"Roll_no":20,"Blood_grp":'A','Admission_no':1431}},'Classes':[7,9]}
dict2['Name']['Rohan']['Marks']=[66,77,43,65,32,54]
dict2['Name']['Krishna']['Marks']=[76,43,21,43,12]
avg1=sum(dict2['Name']['Rohan']['Marks'])/len(dict2['Name']['Rohan']['Marks'])
avg2=sum(dict2['Name']['Krishna']['Marks'])/len(dict2['Name']['Krishna']['Marks'])
d=avg1-avg2
print(int(d))

17


In [ ]:
import ast
L=input()
L1=ast.literal_eval(L)
Lnew=[]
for i in L1:
  if (i%4==0) or (i%9==0):
    Lnew.append(i)
print(Lnew)


[3,8,12,15,18,9,4,27,36,40]
[8, 12, 18, 9, 4, 27, 36, 40]


In [ ]:
n=int(input())#find the sum of primes from 2 to n 
sum=0
for num in range(2,n+1):
  i=0
  for i in range(2,num):
    if num%i==0:
            i=num
            break;
  if i is not num:
      sum=sum+num
print(sum)

10
17


In [ ]:
len(range(2,3))

1

In [ ]:
str1=input()
str2=input()
L1=list(str1)
L2=list(str2)
result=all([char in L2 for char in L1])
print(result)

h3llow
hello
False


In [ ]:
str1=input()
str2=input()
L1=list(str1)
L2=list(str2)
L3=[]
for i in L2:
  j=(i in L1)
  L3.append(j)
if False in L3:
  print('False')
else:
  print('True')


h3llow
hello
False


In [ ]:
import ast
L1=ast.literal_eval(input())
L2=ast.literal_eval(input())
s3=" ".join(L1)
s4=" ".join(L2)
L3=s3.split(" ")
L4=s4.split(" ")
L5=[]
L6=[]
L=[]
for i in L3:
  L5.append(i.lower())
for j in L4:
  L6.append(j.lower())
for i in L5:
  j=(i in L6)
  L.append(j)
if False in L:
  print("False")
else:
  print("True")


  

["I", "love", "programming"]
["Programming", "I love"]
True


In [ ]:
#largest common substring

import ast
#taking the input.
input_str = input()
test_str = ast.literal_eval(input_str)

def check(test_str):
    max_count = 0
    def myfunc(a):
      return len(a)
    test_str.sort(key=myfunc)
    
    for i in range(len(test_str)-1):
      j=i+1
      
      while j<len(test_str):
        #get the starting index of substring in larger substring
        index = test_str[j].find(test_str[i])

        #find will return -1 if the smaller string is not part of the larger string
        if len(test_str[i])>max_count and index!=-1:
            max_count = len(test_str[i])
            target_small = test_str[i]
            target_large = test_str[j]
        j=j+1

    #print the output.               
    print(target_large + ", " + target_small)
    print(target_small)

#calling the function.
check(test_str)


['upGrad', 'substring', 'string', 'graduation', 'buttery', 'BUTTERY']
substring, string
string
