<a href="https://colab.research.google.com/github/Namrata3103-star/Key-Projects/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
input_list=[[9,3,2],
 [4 ,0, 1],
 [5, 8 ,6]]
n_array = np.array(input_list)
for i in range(len(n_array[0,:])):
    n_array=n_array[n_array[:,-1-i].argsort()]
print(n_array)

[[4 0 1]
 [5 8 6]
 [9 3 2]]


In [ ]:
import numpy as np
input_list=[[9,3,2],
 [4 ,0, 1],
 [5, 8 ,6]]
n_array = np.array(input_list)
print(n_array[n_array[:,-3].argsort()])

[[4 0 1]
 [5 8 6]
 [9 3 2]]


In [ ]:
import numpy as np
input_list=[[9,3,2],
 [4 ,0, 1],
 [5, 8 ,6]]
n_array = np.array(input_list)
print(n_array[n_array[:,-2].argsort()])

[[4 0 1]
 [9 3 2]
 [5 8 6]]


In [ ]:
import numpy as np
input_list=[[9,3,2],
 [4 ,0, 1],
 [5, 8 ,6]]
n_array = np.array(input_list)
print(n_array[n_array[:,-1].argsort()])

[[4 0 1]
 [9 3 2]
 [5 8 6]]


In [ ]:
import numpy as np
a = np.array( [7, 10, 2, 4, 13, 16])
med = np.percentile(a, 50)
print(med)

8.5


In [ ]:
import numpy as np
import ast
#input has been taken for you
inp_list=ast.literal_eval(input())
arr=np.array(inp_list)
print(arr[arr[:,:]>3])

[[9,8,7],[6,5,4],[3,2,1]]
[9 8 7 6 5 4]


In [ ]:
import numpy as np
import ast

#input has been taken for you
arr = np.array(ast.literal_eval(input()))
arr1=np.percentile(arr,60)
arr2=round(arr1,2)
print(arr2)

[11, 22, 33, 44 ,55 ,66, 77]
50.6


In [ ]:
import numpy as np
n=int(input())
L=[]
for i in range(0,n):
    L.append(i)
arr=np.array(L)
print(round(np.average(arr),2))
print(round(np.std(arr),2))
print(round(np.var(arr),2))

16
7.5
4.61
21.25


In [ ]:
n = int(input())
import numpy as np 
print(np.eye(n,dtype=int))

3
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
n = int(input())
import numpy as np 
arr=np.zeros((n,n),dtype=int)
arr[0]=1
arr[n-1]=1
j=n-1
for i in range(1,n-1):
    j=j-1
    arr[i,j]=1
print(arr)

5
[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 1 1 1]]


In [ ]:
input_list =[[9,3,2],
 [4, 0, 1],
 [5, 8, 6]]
import numpy as np
n_array = np.array(input_list)
n_array[0,:]

array([9, 3, 2])

In [ ]:
import numpy as np
myarr=np.arange(1,21).reshape(4,5)
print(myarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
import numpy as np
import ast

#input has been taken for you
arr = np.array(ast.literal_eval(input()))
count1=0
count2=0
for i in range(len(arr[0,:])):
  for j in range(len(arr[0,:])):
    if i==j:
      count1=count1+arr[i][j]
    elif (i+j)==len(arr[0,:])-1:
      count2=count2+arr[i][j]
Output=count1+count2
print(Output)


[[1,2,3],  [4,5,6],  [7,8,9]]
25
